specDirName: "generated/specs/openapi" # This path is relative to the basePath
specFilePostfix: "-openapi"
specFileType: "json"
httpStatusCodeFileName: "config/generators/openapi/http-status-codes.csv"
# strategy: DEFINED_TYPES
# strategy: NAMED_OPERATIONS
inheritanceStyle: COMPOSITION
classActionMap:
  CREATE:
    schemaNamePostfix: "Input"
    httpMethod: POST
    successCode: 201
    errorCodes:
     - 409
     - 5XX
  READ:
    schemaNamePostfix: ""
    httpMethod: GET
    successCode: 200
    errorCodes:
      - 404
  UPDATE:
    schemaNamePostfix: "Input"
    httpMethod: PUT
    successCode: 200
    errorCodes:
      - 404
      - 405
  DELETE:
    schemaNamePostfix: ""
    httpMethod: DELETE
    successCode: 204
    errorCodes:
      - 404
resourceIdConfig:
  includeResourceName: false
  resourceIdPostfix: "id" # If includeResourceName is false this is the resourceId name
generate:
  openAPILinks: false
  abstractTypes: true
  containedTypes: true
openapi:
  version: "3.0.3"
  servers:
    - server:
      url: "https://mtt.apigeneration.tech/library/openapi/v1"
      description: "The example Library server"
      variables:
        var1:
          default: demo
          description: An example variable
  info:
    title: "API Generation Library example APIs"
    version: "1.0.0"
    description: "This is the definition of the **API Generation Library example APIs**.  Hopefully it's interesting"
    contact:
      name: "Library API Support"
      url: "http://apigeneration.tech/support"
      email: "support@apigeneration.tech"


